default:
    image: python-custom:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
    - build

build_image:
  image: docker:20.10.12
  stage: build
  services:
    - docker:20.10.12-dind
  before_script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
